Document: shadowsocks-rust
Title: Debian shadowsocks-rust Manual
Author: <insert document author here>
Abstract: This manual describes what shadowsocks-rust is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/shadowsocks-rust/shadowsocks-rust.sgml.gz

Format: postscript
Files: /usr/share/doc/shadowsocks-rust/shadowsocks-rust.ps.gz

Format: text
Files: /usr/share/doc/shadowsocks-rust/shadowsocks-rust.text.gz

Format: HTML
Index: /usr/share/doc/shadowsocks-rust/html/index.html
Files: /usr/share/doc/shadowsocks-rust/html/*.html
